#!/bin/sh

########################################################################
#                                                                      #
# This file is part of Indi's EPUB Makefile project.                   #
#                                                                      #
# Indi's EPUB Makefile project is free software: you can               #
# redistribute it and/or modify it under the terms of the              #
# GNU General Public License as published by the                       #
# Free Software Foundation, either version 3 of the License,           #
# or (at your option) any later version.                               #
#                                                                      #
# Indi's EPUB Makefile project is distributed in the hope that         #
# it will be useful, but WITHOUT ANY WARRANTY; without even            #
# the implied warranty of MERCHANTABILITY or                           #
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License #
# for more details.                                                    #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Indi's EPUB Makefile project.                             #
# If not, see <https://www.gnu.org/licenses/>.                         #
#                                                                      #
########################################################################


set -e
set -u


# For each directory that has a valid test name and a 'clean-test' exe,
# run the exe.

okay=true

for d in */
do
	# Strip trailing slash.
	d="${d%/}"

	# If no directories were found, then 'd' will be '*'. Skip it.
	if [ "${d}" = '*' ]
	then
		continue
	fi

	# Check that the directory has a valid test name.
	if printf '%s' "${d}" | grep -q '^[a-z][a-z0-9]*\(-[a-z0-9]\+\)*$'
	then
		# Check that a 'clean-test' executable exists.
		if [ -f "${d}/clean-test" ] && [ -x "${d}/clean-test" ]
		then
			# Run it.
			( cd -- "${d}" && ./clean-test ) || okay=false
		fi
	fi
done

${okay}
