#!/bin/sh

set -e
set -u

. ../testlib.sh


# Make the book ########################################################

require make -f ../../src/Makefile


# Run epubcheck ########################################################

epubcheck 5.1.0 test-book.epub
