#!/bin/sh

set -e
set -u

. ../testlib.sh


# Make the book ########################################################

require make -f ../../src/Makefile


# Make sure the PNG is in the book #####################################

check unzip -Zs1 test-book.epub OEBPS/image.png >/dev/null 2>/dev/null


# Make sure the SVG is NOT in the book #################################

check ! unzip -Zs1 test-book.epub OEBPS/image.svg >/dev/null 2>/dev/null


# Run epubcheck ########################################################

epubcheck 5.1.0 test-book.epub
