name: Bug report
description: Report broken or bizarre behaviour
labels: bug
assignees: DarkerStar
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal steps to reproduce the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What is the expected behaviour?

  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system are you using?"
      placeholder: "example: Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: make
    attributes:
      label: Make version
      description: "Which version of make system are you using?"
      placeholder: "example: GNU Make 4.3"
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?
