name: Query
description: Ask a question
assignees: DarkerStar
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to ask?
    validations:
      required: true
